# Generated by Django 3.1 on 2023-10-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20231017_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_payment_signature',
        ),
    ]
